/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package chat_application_java;

import java.io.*;
import java.net.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.awt.image.BufferedImage;
import java.lang.*;
import java.nio.ByteBuffer;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;


/**
 *
 * @author Muhammad Moiz Tahir
 */


public class MessageWindowClient extends javax.swing.JFrame implements MessageListener {

    private static ChatClient client;
    private static String login;
    

    private DefaultListModel<String> listModel = new DefaultListModel<>();


     public MessageWindowClient(ChatClient client, String login)  {
        
         this.client = client;
        this.login = login;

        client.addMessageListener(this);
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        close_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        username_label = new javax.swing.JLabel();
        userid_label = new javax.swing.JLabel();
        clear_icon = new javax.swing.JLabel();
        delete_icon = new javax.swing.JLabel();
        back_button_icon = new javax.swing.JLabel();
        image_send = new javax.swing.JButton();
        Text_field = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        message_area = new javax.swing.JList<>();
        send_button = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(52, 152, 219));

        close_btn.setBackground(new java.awt.Color(52, 152, 219));
        close_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        close_btn.setText("X");
        close_btn.setBorder(null);
        close_btn.setBorderPainted(false);
        close_btn.setContentAreaFilled(false);
        close_btn.setFocusPainted(false);
        close_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_btnClose_btn(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));

        username_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        username_label.setForeground(new java.awt.Color(255, 255, 255));
        username_label.setText("username:");

        userid_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userid_label.setForeground(new java.awt.Color(255, 255, 255));
        userid_label.setText("userid:");

        clear_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chat_application_java/icons8-broom-26.png"))); // NOI18N
        clear_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clear_iconMouseClicked(evt);
            }
        });

        delete_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chat_application_java/icons8-close-window-30.png"))); // NOI18N
        delete_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_iconMouseClicked(evt);
            }
        });

        back_button_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chat_application_java/icons8-back-to-30.png"))); // NOI18N
        back_button_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_button_iconMouseClicked(evt);
            }
        });

        image_send.setText("image");
        image_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                image_sendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back_button_icon)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username_label)
                    .addComponent(userid_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(image_send)
                .addGap(18, 18, 18)
                .addComponent(delete_icon)
                .addGap(18, 18, 18)
                .addComponent(clear_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clear_icon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(image_send)
                    .addComponent(delete_icon)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(7, 7, 7)
                            .addComponent(back_button_icon))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(username_label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userid_label, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 426, Short.MAX_VALUE)
                .addComponent(close_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(close_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Text_field.setText(" Type your message here...");
        Text_field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Text_fieldText_Area_action(evt);
            }
        });
        Text_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_fieldAction(evt);
            }
        });

        jScrollPane1.setViewportView(message_area);

        send_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chat_application_java/icons8-send-30.png"))); // NOI18N
        send_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                send_buttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Text_field, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(send_button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(send_button)
                    .addComponent(Text_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void send_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_send_buttonMouseClicked
        // TODO add your handling code here:
        try {
            String text = Text_field.getText();
            client.msg(login, text);
            message_area.setModel(listModel);
            listModel.addElement("You: " + text);
            Text_field.setText("");
        } catch (IOException e1) {
            e1.printStackTrace();
        }
    }//GEN-LAST:event_send_buttonMouseClicked

    private void back_button_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_button_iconMouseClicked
        // TODO add your handling code here:
        this.dispose();
        UserListPane obj = new UserListPane(client);
        obj.setVisible(true);
    }//GEN-LAST:event_back_button_iconMouseClicked

    private void delete_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_iconMouseClicked
        int index = message_area.getSelectedIndex();
        listModel.removeElementAt(index);
    }//GEN-LAST:event_delete_iconMouseClicked

    private void clear_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clear_iconMouseClicked
        // TODO add your handling code here:
        listModel.clear();
        message_area.setModel(listModel);
    }//GEN-LAST:event_clear_iconMouseClicked

    private void close_btnClose_btn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_btnClose_btn
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_close_btnClose_btn

    private void Text_fieldAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_fieldAction
        // TODO add your handling code here:
        try {
            String text = Text_field.getText();
            client.msg(login, text);
            message_area.setModel(listModel);
            listModel.addElement("You: " + text);
            Text_field.setText("");
        } catch (IOException e1) {
            e1.printStackTrace();
        }
    }//GEN-LAST:event_Text_fieldAction

    private void Text_fieldText_Area_action(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Text_fieldText_Area_action
        // TODO add your handling code here:
        Text_field.setText("");
    }//GEN-LAST:event_Text_fieldText_Area_action

    private void image_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_image_sendActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_image_sendActionPerformed

    
    
    
     @Override
    public void onMessage(String fromLogin, String msgBody) {
        if (login.equalsIgnoreCase(fromLogin)) {
            String line = fromLogin + ": " + msgBody;
            listModel.addElement(line);
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MessageWindowClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MessageWindowClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MessageWindowClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MessageWindowClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //String SetUserName = JOptionPane.showInputDialog(null,"please enter your name:","MOIZ chat app",JOptionPane.PLAIN_MESSAGE);
                //String servername="localhost";
                try{
                new MessageWindowClient(client,login).setVisible(true);
                }
                catch(Exception ex){
                System.out.println(ex.getMessage());
                }
            }
        });
        
        }

   
public Vector jList_Vector;
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Text_field;
    private javax.swing.JLabel back_button_icon;
    private javax.swing.JLabel clear_icon;
    private javax.swing.JButton close_btn;
    private javax.swing.JLabel delete_icon;
    private javax.swing.JButton image_send;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> message_area;
    private javax.swing.JLabel send_button;
    private javax.swing.JLabel userid_label;
    private javax.swing.JLabel username_label;
    // End of variables declaration//GEN-END:variables
}
// TODO add your handling code here:

